# Generated by Django 3.1.6 on 2021-02-21 13:15

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=stdimage.models.StdImageField(blank=True, upload_to='images/'),
        ),
    ]
